fetched_quotes = [
    {
        "q": "Those who attain the middle Dominate the whole.",
        "a": "Ming-Dao Deng",
        "c": "47",
        "h": "<blockquote>&ldquo;Those who attain the middle Dominate the whole.&rdquo; &mdash; <footer>Ming-Dao Deng</footer></blockquote>",
    },
    {
        "q": "Help others for all the times that you have been ignored. Be kind to others, for all the times that you have been scorned.",
        "a": "Ming-Dao Deng",
        "c": "122",
        "h": "<blockquote>&ldquo;Help others for all the times that you have been ignored. Be kind to others, for all the times that you have been scorned.&rdquo; &mdash; <footer>Ming-Dao Deng</footer></blockquote>",
    },
    {
        "q": "If you don't read the newspaper, you're uninformed. If you read the newspaper, you're misinformed.",
        "a": "Mark Twain",
        "c": "98",
        "h": "<blockquote>&ldquo;If you don't read the newspaper, you're uninformed. If you read the newspaper, you're misinformed.&rdquo; &mdash; <footer>Mark Twain</footer></blockquote>",
    },
    {
        "q": "Do not ignore the passion that burns in you. Spend time to discover your gift.",
        "a": "Steve Harvey",
        "c": "78",
        "h": "<blockquote>&ldquo;Do not ignore the passion that burns in you. Spend time to discover your gift.&rdquo; &mdash; <footer>Steve Harvey</footer></blockquote>",
    },
    {
        "q": "Discipline is the bridge between goals and accomplishment.",
        "a": "Jim Rohn",
        "c": "58",
        "h": "<blockquote>&ldquo;Discipline is the bridge between goals and accomplishment.&rdquo; &mdash; <footer>Jim Rohn</footer></blockquote>",
    },
    {
        "q": "Change is hardest at the beginning, messiest in the middle and best at the end.",
        "a": "Robin Sharma",
        "c": "79",
        "h": "<blockquote>&ldquo;Change is hardest at the beginning, messiest in the middle and best at the end.&rdquo; &mdash; <footer>Robin Sharma</footer></blockquote>",
    },
    {
        "q": "Correct what you can. Learn from what you can't.",
        "a": "Toni Morrison",
        "c": "48",
        "h": "<blockquote>&ldquo;Correct what you can. Learn from what you can't.&rdquo; &mdash; <footer>Toni Morrison</footer></blockquote>",
    },
    {
        "q": "Relax. Nothing is under control.",
        "a": "Adi Da Samraj",
        "c": "32",
        "h": "<blockquote>&ldquo;Relax. Nothing is under control.&rdquo; &mdash; <footer>Adi Da Samraj</footer></blockquote>",
    },
    {
        "q": "You are the sky. Everything else - it's just the weather.",
        "a": "Pema Chodron",
        "c": "57",
        "h": "<blockquote>&ldquo;You are the sky. Everything else - it's just the weather.&rdquo; &mdash; <footer>Pema Chodron</footer></blockquote>",
    },
    {
        "q": "Words used to attract the dull of wit are not to be relied on.",
        "a": "Huang Po",
        "c": "62",
        "h": "<blockquote>&ldquo;Words used to attract the dull of wit are not to be relied on.&rdquo; &mdash; <footer>Huang Po</footer></blockquote>",
    },
    {
        "q": "The art of being happy lies in the power of extracting happiness from common things.",
        "a": "Henry Ward Beecher",
        "c": "84",
        "h": "<blockquote>&ldquo;The art of being happy lies in the power of extracting happiness from common things.&rdquo; &mdash; <footer>Henry Ward Beecher</footer></blockquote>",
    },
    {
        "q": "Experience is simply the name we give our mistakes. ",
        "a": "Oscar Wilde",
        "c": "52",
        "h": "<blockquote>&ldquo;Experience is simply the name we give our mistakes. &rdquo; &mdash; <footer>Oscar Wilde</footer></blockquote>",
    },
    {
        "q": "A man is not called wise because he talks and talks again; but if he is peaceful, loving and fearless then he is in truth called wise. ",
        "a": "Buddha",
        "c": "135",
        "h": "<blockquote>&ldquo;A man is not called wise because he talks and talks again; but if he is peaceful, loving and fearless then he is in truth called wise. &rdquo; &mdash; <footer>Buddha</footer></blockquote>",
    },
    {
        "q": "Perfection is not attainable, but if we chase perfection we can catch excellence.",
        "a": "Vince Lombardi",
        "c": "81",
        "h": "<blockquote>&ldquo;Perfection is not attainable, but if we chase perfection we can catch excellence.&rdquo; &mdash; <footer>Vince Lombardi</footer></blockquote>",
    },
    {
        "q": "Live the moment for the moment.",
        "a": "Michael Jordan",
        "c": "31",
        "h": "<blockquote>&ldquo;Live the moment for the moment.&rdquo; &mdash; <footer>Michael Jordan</footer></blockquote>",
    },
    {
        "q": "Success and failure come and go, but don't let them define you. It's who you are that matters.",
        "a": "Kamal Ravikant",
        "c": "94",
        "h": "<blockquote>&ldquo;Success and failure come and go, but don't let them define you. It's who you are that matters.&rdquo; &mdash; <footer>Kamal Ravikant</footer></blockquote>",
    },
    {
        "q": "It's not the size of the dog in the fight, it's the size of the fight in the dog.",
        "a": "Mark Twain",
        "c": "81",
        "h": "<blockquote>&ldquo;It's not the size of the dog in the fight, it's the size of the fight in the dog.&rdquo; &mdash; <footer>Mark Twain</footer></blockquote>",
    },
    {
        "q": "Until we can manage time, we can manage nothing else.",
        "a": "Peter Drucker",
        "c": "53",
        "h": "<blockquote>&ldquo;Until we can manage time, we can manage nothing else.&rdquo; &mdash; <footer>Peter Drucker</footer></blockquote>",
    },
    {
        "q": "Those who know, do. Those that understand, teach.",
        "a": "Aristotle",
        "c": "49",
        "h": "<blockquote>&ldquo;Those who know, do. Those that understand, teach.&rdquo; &mdash; <footer>Aristotle</footer></blockquote>",
    },
    {
        "q": "Tenderness and kindness are not signs of weakness and despair, but manifestations of strength and resolution.",
        "a": "Kahlil Gibran",
        "c": "109",
        "h": "<blockquote>&ldquo;Tenderness and kindness are not signs of weakness and despair, but manifestations of strength and resolution.&rdquo; &mdash; <footer>Kahlil Gibran</footer></blockquote>",
    },
    {
        "q": "Watch what you say, and whaterver you say, practice it.",
        "a": "Soyen Shaku",
        "c": "55",
        "h": "<blockquote>&ldquo;Watch what you say, and whaterver you say, practice it.&rdquo; &mdash; <footer>Soyen Shaku</footer></blockquote>",
    },
    {
        "q": "Money poisons you when you've got it, and starves you when you haven't.",
        "a": "D. H. Lawrence",
        "c": "71",
        "h": "<blockquote>&ldquo;Money poisons you when you've got it, and starves you when you haven't.&rdquo; &mdash; <footer>D. H. Lawrence</footer></blockquote>",
    },
    {
        "q": "No matter how smart we may think we are, no matter how committed we are to our truth, we can lose our way.",
        "a": "Kamal Ravikant",
        "c": "106",
        "h": "<blockquote>&ldquo;No matter how smart we may think we are, no matter how committed we are to our truth, we can lose our way.&rdquo; &mdash; <footer>Kamal Ravikant</footer></blockquote>",
    },
    {
        "q": "Everybody needs a passion. That's what keeps life interesting.",
        "a": "Betty White",
        "c": "62",
        "h": "<blockquote>&ldquo;Everybody needs a passion. That's what keeps life interesting.&rdquo; &mdash; <footer>Betty White</footer></blockquote>",
    },
    {
        "q": "The key to success is to focus our conscious mind on things we desire not things we fear. ",
        "a": "Brian Tracy",
        "c": "90",
        "h": "<blockquote>&ldquo;The key to success is to focus our conscious mind on things we desire not things we fear. &rdquo; &mdash; <footer>Brian Tracy</footer></blockquote>",
    },
    {
        "q": "Be brave to stand for what you believe in even if you stand alone.",
        "a": "Roy T. Bennett",
        "c": "66",
        "h": "<blockquote>&ldquo;Be brave to stand for what you believe in even if you stand alone.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>",
    },
    {
        "q": "I have never let my schooling interfere with my education.",
        "a": "Mark Twain",
        "c": "58",
        "h": "<blockquote>&ldquo;I have never let my schooling interfere with my education.&rdquo; &mdash; <footer>Mark Twain</footer></blockquote>",
    },
    {
        "q": "Too much sanity may be madness and the maddest of all, to see life as it is and not as it should be. ",
        "a": "Miguel de Cervantes",
        "c": "101",
        "h": "<blockquote>&ldquo;Too much sanity may be madness and the maddest of all, to see life as it is and not as it should be. &rdquo; &mdash; <footer>Miguel de Cervantes</footer></blockquote>",
    },
    {
        "q": "Life is a challenge, meet it! Life is a dream, realize it! Life is a game, play it! Life is love, enjoy it!",
        "a": "Sathya Sai Baba",
        "c": "107",
        "h": "<blockquote>&ldquo;Life is a challenge, meet it! Life is a dream, realize it! Life is a game, play it! Life is love, enjoy it!&rdquo; &mdash; <footer>Sathya Sai Baba</footer></blockquote>",
    },
    {
        "q": "The world makes way for the man who knows where he is going.",
        "a": "Ralph Waldo Emerson",
        "c": "60",
        "h": "<blockquote>&ldquo;The world makes way for the man who knows where he is going.&rdquo; &mdash; <footer>Ralph Waldo Emerson</footer></blockquote>",
    },
    {
        "q": "I am not what happened to me, I am what I choose to become.",
        "a": "Carl Jung",
        "c": "59",
        "h": "<blockquote>&ldquo;I am not what happened to me, I am what I choose to become.&rdquo; &mdash; <footer>Carl Jung</footer></blockquote>",
    },
    {
        "q": "Everything eaten is killed. Every meal is a sacrifice.",
        "a": "Adi Da Samraj",
        "c": "54",
        "h": "<blockquote>&ldquo;Everything eaten is killed. Every meal is a sacrifice.&rdquo; &mdash; <footer>Adi Da Samraj</footer></blockquote>",
    },
    {
        "q": "The outer conditions of a person's life will always be found to reflect their inner beliefs.",
        "a": "James Allen",
        "c": "92",
        "h": "<blockquote>&ldquo;The outer conditions of a person's life will always be found to reflect their inner beliefs.&rdquo; &mdash; <footer>James Allen</footer></blockquote>",
    },
    {
        "q": "Normal is the average of deviance.",
        "a": "Rita Mae Brown",
        "c": "34",
        "h": "<blockquote>&ldquo;Normal is the average of deviance.&rdquo; &mdash; <footer>Rita Mae Brown</footer></blockquote>",
    },
    {
        "q": "Don't change your mind just because people are offended; change your mind if you're wrong.",
        "a": "Criss Jami",
        "c": "90",
        "h": "<blockquote>&ldquo;Don't change your mind just because people are offended; change your mind if you're wrong.&rdquo; &mdash; <footer>Criss Jami</footer></blockquote>",
    },
    {
        "q": "There are two ways of seeing: with the body and with the soul. The body's sight can sometimes forget, but the soul remembers forever.",
        "a": "Alexandre Dumas",
        "c": "133",
        "h": "<blockquote>&ldquo;There are two ways of seeing: with the body and with the soul. The body's sight can sometimes forget, but the soul remembers forever.&rdquo; &mdash; <footer>Alexandre Dumas</footer></blockquote>",
    },
    {
        "q": "Problems remain as problems because people are busy defending them rather than finding solutions.",
        "a": "Celestine Chua",
        "c": "97",
        "h": "<blockquote>&ldquo;Problems remain as problems because people are busy defending them rather than finding solutions.&rdquo; &mdash; <footer>Celestine Chua</footer></blockquote>",
    },
    {
        "q": "No man is happy who does not think himself so.",
        "a": "Norman Vincent Peale",
        "c": "46",
        "h": "<blockquote>&ldquo;No man is happy who does not think himself so.&rdquo; &mdash; <footer>Norman Vincent Peale</footer></blockquote>",
    },
    {
        "q": "Riches don't make a man rich, they only make him busier.",
        "a": "Christopher Columbus",
        "c": "56",
        "h": "<blockquote>&ldquo;Riches don't make a man rich, they only make him busier.&rdquo; &mdash; <footer>Christopher Columbus</footer></blockquote>",
    },
    {
        "q": "Never do to others what you would not like them to do to you. ",
        "a": "Confucius",
        "c": "62",
        "h": "<blockquote>&ldquo;Never do to others what you would not like them to do to you. &rdquo; &mdash; <footer>Confucius</footer></blockquote>",
    },
    {
        "q": "People who say it cannot be done should not interrupt those who are doing it.",
        "a": "George Bernard Shaw",
        "c": "77",
        "h": "<blockquote>&ldquo;People who say it cannot be done should not interrupt those who are doing it.&rdquo; &mdash; <footer>George Bernard Shaw</footer></blockquote>",
    },
    {
        "q": "Often we pass beside happiness without seeing it, without looking at it, or even if we have seen and looked at it, without recognizing it.",
        "a": "Alexandre Dumas",
        "c": "138",
        "h": "<blockquote>&ldquo;Often we pass beside happiness without seeing it, without looking at it, or even if we have seen and looked at it, without recognizing it.&rdquo; &mdash; <footer>Alexandre Dumas</footer></blockquote>",
    },
    {
        "q": "A tiny change today brings a dramatically different tomorrow.",
        "a": "Richard Bach",
        "c": "61",
        "h": "<blockquote>&ldquo;A tiny change today brings a dramatically different tomorrow.&rdquo; &mdash; <footer>Richard Bach</footer></blockquote>",
    },
    {
        "q": "Life should be touched, not strangled.  ",
        "a": "Ray Bradbury",
        "c": "40",
        "h": "<blockquote>&ldquo;Life should be touched, not strangled.  &rdquo; &mdash; <footer>Ray Bradbury</footer></blockquote>",
    },
    {
        "q": "There is no medicine like hope, no incentive so great, and no tonic so powerful as expectation of something tomorrow. ",
        "a": "Orison Swett Marden",
        "c": "118",
        "h": "<blockquote>&ldquo;There is no medicine like hope, no incentive so great, and no tonic so powerful as expectation of something tomorrow. &rdquo; &mdash; <footer>Orison Swett Marden</footer></blockquote>",
    },
    {
        "q": "Some of us learn from other people's mistakes and the rest of us have to be other people.  ",
        "a": "Zig Ziglar",
        "c": "91",
        "h": "<blockquote>&ldquo;Some of us learn from other people's mistakes and the rest of us have to be other people.  &rdquo; &mdash; <footer>Zig Ziglar</footer></blockquote>",
    },
    {
        "q": "If you don't find the time, if you don't do the work, you don't get the results.",
        "a": "Arnold Schwarzenegger",
        "c": "80",
        "h": "<blockquote>&ldquo;If you don't find the time, if you don't do the work, you don't get the results.&rdquo; &mdash; <footer>Arnold Schwarzenegger</footer></blockquote>",
    },
    {
        "q": "Allow motion to equal emotion.",
        "a": "Elbert Hubbard",
        "c": "30",
        "h": "<blockquote>&ldquo;Allow motion to equal emotion.&rdquo; &mdash; <footer>Elbert Hubbard</footer></blockquote>",
    },
    {
        "q": "Setting goals is the first step in turning the invisible into the visible.",
        "a": "Tony Robbins",
        "c": "74",
        "h": "<blockquote>&ldquo;Setting goals is the first step in turning the invisible into the visible.&rdquo; &mdash; <footer>Tony Robbins</footer></blockquote>",
    },
    {
        "q": "Change the changeable, accept the unchangeable, and remove yourself from the unacceptable. ",
        "a": "Denis Waitley",
        "c": "91",
        "h": "<blockquote>&ldquo;Change the changeable, accept the unchangeable, and remove yourself from the unacceptable. &rdquo; &mdash; <footer>Denis Waitley</footer></blockquote>",
    },
]
