"""empty message

Revision ID: b39142088a06
Revises: 281c2ebcb77d
Create Date: 2022-04-21 16:41:27.436366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b39142088a06'
down_revision = '281c2ebcb77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timed_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.SmallInteger(), nullable=False),
    sa.Column('accuracy', sa.Float(precision=2), nullable=False),
    sa.Column('wpm', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timed_record')
    # ### end Alembic commands ###
