"""empty message

Revision ID: 76b13d415da9
Revises: b39142088a06
Create Date: 2022-04-22 11:03:28.267474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76b13d415da9'
down_revision = 'b39142088a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timed_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.SmallInteger(), nullable=False),
    sa.Column('accuracy', sa.Float(precision=2), nullable=False),
    sa.Column('wpm', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('timed_record')
    op.add_column('comments', sa.Column('timed_record_id', sa.Integer(), nullable=True))
    op.alter_column('comments', 'record_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'comments', 'timed_records', ['timed_record_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.alter_column('comments', 'record_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('comments', 'timed_record_id')
    op.create_table('timed_record',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('minute', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('accuracy', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('wpm', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='timed_record_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='timed_record_pkey')
    )
    op.drop_table('timed_records')
    # ### end Alembic commands ###
