"""empty message

Revision ID: 1e2b88d5c846
Revises: c14de92ddd0f
Create Date: 2022-04-12 17:48:17.435105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2b88d5c846'
down_revision = 'c14de92ddd0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('char_count', sa.Integer(), nullable=False))
    op.drop_column('quotes', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('quotes', 'char_count')
    # ### end Alembic commands ###
