"""empty message

Revision ID: c14de92ddd0f
Revises: 90266498c8c3
Create Date: 2022-04-12 16:59:57.486666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14de92ddd0f'
down_revision = '90266498c8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_record_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'records', ['record_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('records_user_id_fkey', 'records', type_='foreignkey')
    op.drop_constraint('records_quote_id_fkey', 'records', type_='foreignkey')
    op.create_foreign_key(None, 'records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'records', 'quotes', ['quote_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.create_foreign_key('records_quote_id_fkey', 'records', 'quotes', ['quote_id'], ['id'])
    op.create_foreign_key('records_user_id_fkey', 'records', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_record_id_fkey', 'comments', 'records', ['record_id'], ['id'])
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
